### PR TITLE
add nvm support

### PR DESCRIPTION
**Pull request by Chive**

### CODE REVIEW

**Comment by FinalAngel** [comment]
@Chive this boilerplate does not require node support, only:
- https://github.com/aldryn/aldryn-boilerplate-bootstrap3
- https://github.com/divio/djangocms-boilerplate-webpack

In addition, do we need the extra scripts? Cause they will also be copied into the project itself.

**Comment by Chive** [comment]
oops, wrong repo. @FinalAngel is aldryn-boilerplate-bootstrap3 still supported? And yes, the scripts are needed since they will be run for every build.

**Comment by FinalAngel** [comment]
@Chive yeah both, aldryn-bootstrap-boilerplate and webpack are in use. If the scripts are required, please move them to ``tools/docker`` in both cases

**Comment by Chive** [comment]
@FinalAngel `docker` is not very descriptive - how about `tools/build` instead?

**Comment by FinalAngel** [comment]
@Chive sure :)

**Pull request closed without merging**
